### PR TITLE
fix: avoid pushing invalid addr args

### LINKED ISSUE #194: Failed to parse address :0
I got this error from frontend when using gtctl to start a baremetal cluster:

```
Error: 0: Failed to start frontend, at ../greptimedb-dev/src/cmd/src/frontend.rs:279:14
1: Failed to parse address :0
2: AddrParseError(Socket)
```

From gtctl's log, the frontend command is 
```
component 'frontend.0' binary '../target/greptimedb-dev/release/greptime' (pid '3908968') exited with error: exit status 1
args: '[--log-level=info frontend start --metasrv-addr=127.0.0.1:3002 --http-addr=:0 --rpc-addr=:0 --mysql-addr=:0 --postgres-addr=:0 --opentsdb-addr=:0 -c=../greptimedb-dev/config/frontend.example.toml]'
```

It might be caused by the default addr parameter:
```
--http-addr=:0 --rpc-addr=:0 --mysql-addr=:0 --postgres-addr=:0 --opentsdb-addr=:0
```

gtctl config file:
```yaml
cluster:
  name: mycluster # name of the cluster
  artifact:
    local: "../target/greptimedb-dev/release/greptime"
  frontend:
    replicas: 1
    config: '../greptimedb-dev/config/frontend.example.toml'
  datanode:
    replicas: 3
    rpcAddr: 0.0.0.0:14100
    mysqlAddr: 0.0.0.0:14200
    httpAddr: 0.0.0.0:14300
    config: '../greptimedb-dev/config/datanode.example.toml'
  meta:
    replicas: 1
    storeAddr: 127.0.0.1:2379
    serverAddr: 127.0.0.1:3002
    httpAddr: 0.0.0.0:14001
    config: '../greptimedb-dev/config/metasrv.example.toml'

etcd:
  artifact:
    local: "/usr/bin/etcd"
```

### PR DESCRIPTION
**Pull request by waynexia**
closes #194

The generated command now becomes 
```
 run 'frontend.0' binary '../target/greptimedb-dev/release/greptime' with args: '[--log-level=info frontend start --metasrv-addr=127.0.0.1:3002 -c=../config/frontend.example.toml]', log: '~/.gtctl/mycluster/logs/frontend.0'
```

without invalid args

### CODE REVIEW

File: pkg/components/frontend.go [hunk 1]
```diff
@@ -141,10 +142,29 @@ func (f *frontend) IsRunning(_ context.Context) bool {
 	return true
 }
 
-func generateAddrArg(addr string, nodeId int) string {
+// formatAddrArg formats the given addr and nodeId to a valid socket string.
+// This function will return an empty string when the given addr is empty.
+func formatAddrArg(addr string, nodeId int) string {
+	// return empty result if the address is not specified
+	if len(addr) == 0 {
```
Comment (tisonkun) [inline pkg/components/frontend.go]: Will GreptimeDB use a default value if this arg is empty?

**Review by tisonkun — COMMENTED** [review]
Perhaps also for `generateMetaSrvAddr` and `generateDatanodeAddr`

File: pkg/components/frontend.go (hunk 1 above)
Comment (waynexia) [reply pkg/components/frontend.go]: All three components have a default value. And `gtctl` will also pass a config file which has related options.

**Comment by waynexia** [comment]
The e2e test failure seems unrelated to this change. It's caused by the partition rule change from DB. We shall fix it in a separate PR

File: pkg/components/frontend.go (hunk 1 above)
Comment (tisonkun) [reply pkg/components/frontend.go]: Got. Than we may also return `""` for  `generateMetaSrvAddr` and `generateDatanodeAddr ` if `addr` is empty.

Comment (waynexia) [reply pkg/components/frontend.go]: 👍 I've refactored them to use the same function in https://github.com/GreptimeTeam/gtctl/pull/195/commits/cc591fa6c0e5e8abbb6a5977ebe6dfb8f5810cb8

**Comment by tisonkun** [comment]
@waynexia CI failed to your recent PARTITION syntax change - https://github.com/GreptimeTeam/greptimedb/pull/3347

Perhaps you can fix it also?

**Comment by tisonkun** [comment]
Said now this sql is invalid:

```sql
	createTableSQL = `CREATE TABLE dist_table (
                        ts TIMESTAMP DEFAULT current_timestamp(),
                        n INT,
    					row_id INT,
                        TIME INDEX (ts),
                        PRIMARY KEY(n)
                     )
                     PARTITION BY RANGE COLUMNS (n) (
    				 	PARTITION r0 VALUES LESS THAN (5),
    					PARTITION r1 VALUES LESS THAN (9),
    					PARTITION r2 VALUES LESS THAN (MAXVALUE),
					)`
```

**Comment by tisonkun** [comment]
Or let's fix the e2e first in another PR first, then we can merge this PR ensuring the tests passed.

**Comment by waynexia** [comment]
>The e2e test failure seems unrelated to this change. It's caused by the partition rule change from DB. We shall fix it in a separate PR

That seems unrelated to this change. Maybe we should pin the db version in the e2e test to also prevent future breaking changes. As those CI are not run in the main repo against every new commit.

**Comment by tisonkun** [comment]
> That seems unrelated to this change. Maybe we should pin the db version in the e2e tes

Make sense. Anyway let's avoid merging patch without CI green if possible. (The failed test is unrelated, but it terminates following tests I guess?)

**Comment by waynexia** [comment]
>The failed test is unrelated, but it terminates following tests I guess?

For this specific case, SQL is run after the cluster is up.

**Comment by zyy17** [comment]
@waynexia Are you fixing the failure of e2e test? If not, let me fix it in a sperate PR.

**Comment by waynexia** [comment]
> @waynexia Are you fixing the failure of e2e test? If not, let me fix it in a sperate PR.

Trying... https://github.com/GreptimeTeam/gtctl/issues/196

**Comment by daviderli614** [comment]
@waynexia The e2e failure will be fixed in this pr: https://github.com/GreptimeTeam/gtctl/pull/197
Can rebase it when merge.

**Review by tisonkun — APPROVED** [review]
